# Makefile for usr.bin

.include <bsd.own.mk>

# NetBSD imports
SUBDIR= deroff indent m4 spell stat tic sed mkdep uniq

# Non-NetBSD imports
SUBDIR+= ministat

# Minix commands
SUBDIR+= top mkimage

.include <bsd.subdir.mk>
