# Makefile for usr.bin

.include <bsd.own.mk>

# NetBSD imports
SUBDIR= indent login m4 stat tic sed mkdep passwd uniq

# Non-NetBSD imports
SUBDIR+= ministat

# Minix commands
SUBDIR+= top mkimage

.include <bsd.subdir.mk>
