# Makefile for usr.bin

.include <bsd.own.mk>

# NetBSD imports
SUBDIR= chpass indent login m4 newgrp stat tic sed mkdep passwd su uniq

# Non-NetBSD imports
SUBDIR+= ministat

# Minix commands
SUBDIR+= top mkimage

.include <bsd.subdir.mk>
